name: "CivModern Release Gradle CI"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up JDK 21"
        uses: "actions/setup-java@v3"
        with:
          java-version: 21
          distribution: "corretto"
          cache: "gradle"

      - name: "Compiling CivModern"
        run: "./gradlew build"

      - name: "Publishing CivModern"
        run: |
          for file in $(find "dist/" -maxdepth 1 -type f -name "*.jar"); do
            echo "Uploading $file"
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
